# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode8
podfile: AKMediaViewerExample/Podfile

script:
- xcodebuild -workspace AKMediaViewerExample/AKMediaViewerExample.xcworkspace -scheme AKMediaViewerExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
